### ISSUE TITLE
BUG: window not found error when reloading the /google page 

### ISSUE THREAD

**Issue by BingHawk** [BingHawk/SE4GI_project#14]
To reproduce: navigate to /google by clicking on maps, then reload the webpage.

**Comment by imostafaaa** [comment]
Done, you can pull dev2 and try it

**Comment by BingHawk** [comment]
> Done, you can pull dev2 and try it

Issue a pull request and I will review!

**Comment by BingHawk** [comment]
Works for chrome and firefox
