### ISSUE TITLE
List of cities for Dropdown/Search bar

### ISSUE THREAD

**Issue by AlbaLunner** [BingHawk/SE4GI_project#15]
Query v2/cities from OpenAQ, and make an endpoint that shows list of cities, push to Github
json: {"cities": [city1, city2, ... cityN]}

**Comment by AhmedAbdalgader** [comment]
@app.route('/api/cities')
def get_cityName():
    r=requests.get("https://u50g7n0cbj.execute-api.us-east-1.amazonaws.com/v2/cities?limit=1000&page=1&offset=0&sort=asc&country=IT&order_by=city")

    citiesname=[]
    print(r.json()['results'][0])
    # return r.json()
    for result in r.json()['results']:
        try:
            cityname = result['city']
        except KeyError:
            continue
        citiesname.append(cityname)
    response = json.dumps({'cities': citiesname})
    return response
