### ISSUE TITLE
Make city endpoint send only necessary data

### ISSUE THREAD

**Issue by BingHawk** [BingHawk/SE4GI_project#16]
Make city endpoint only send the data described here:  https://docs.google.com/spreadsheets/d/1ugmoeM799X7jM-eyEqmReM4pzTT_hkMXt5YoiRXflb8/edit#gid=0 

NB: data from "current data" column. 

aggregate data so there is only one value per city

Decide on a JSON format and redo the format if needed

**Comment by AhmedAbdalgader** [comment]
do you mean by 'only value per city?
only value per city per each parameter, right?

**Comment by AhmedAbdalgader** [comment]
I have managed to extract the needed data, but I am not able to limit the loop over on sub-nested array 'parameters' for each element "city", it combines them all.

**Comment by BingHawk** [comment]
>  I have managed to extract the needed data, but I am not able to limit the loop over on sub-nested array 'parameters' for each element "city", it combines them all.

If you want to, I can look at it. Push the change to GitHub if so

**Comment by AhmedAbdalgader** [comment]
I will try more.
 if didn't work, I will.

**Comment by BingHawk** [comment]
Here is the JSON format if that helps :)
`{
	cityName: String,
	lastUpdate: DateTime,
	Meassurements: [{
		particleName: String,
		unit: String,
		value: Float
	}, {
		particleName: String,
		unit: String,
		value: Float
	}]
}`

**Comment by BingHawk** [comment]
Filtering is done, calculating average still to be done
