### ISSUE TITLE
Feat: Make map markers clickable

### ISSUE THREAD

**Issue by BingHawk** [BingHawk/SE4GI_project#21]
Make markers clickable and make sure that city name and values for each particle is showing

**Comment by BingHawk** [comment]
Some challenges but going forward

**Comment by ehorem** [comment]
Would like to use something like:
{{ parseFloat.($variable).toFixed(2) }} on the decimals. Good idea to manage them in the backend instead. 

Dates need to be shortened, probably with a function because a little googling said vue doesn't have options for managing date format directly.

**Comment by BingHawk** [comment]
closed by merge of pr #49
