### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by BingHawk** [BingHawk/SE4GI_project#29]
- [x] Design how login should work
- [x] Make backend code for login
- [x] make frontend code for login

**Comment by AhmedAbdalgader** [comment]
can I work on the last two tasks without the CSS part of the third one?

**Comment by BingHawk** [comment]
When I say "should work", I mean for the user, not how it should look. like, should user be prompted to log in at once when entering the page or should the user be allowed to use the website without logging in etc. 

Also the technical stuff: What data should be sent between front and back end? what information should be sent to the database? Where should the comparison of passwords sit? Should we use any libraries for login functionality? 

How could you start coding without knowing what to code? What would be your first step if you wanted to start coding?

**Comment by AhmedAbdalgader** [comment]
well, I recommend just logging in will add only one feature when the user logs in, the map zooms to the last location(city) that he searched for.
Any more ideas it will get more complex.
On that note, apart from the data that he inserts, the name of the city also saved before logging out

**Comment by BingHawk** [comment]
Aight! Think that is a good idea. I'll add a field in the db to store the last chosen city. 

Should the user story look like this then: 
1. User goes to the website, it shows up as normal (not logged in). 
2. User clicks login icon in top right (currently some dudes face, will be changed)
3. Login-popup apears where the user can input username and password or click "register".
4. User clicks "register" and inputs password and username which is stored in the db
5. login-popup disappears. user does searches. 
6. User clicks logg out (also in top corner) or closes the website. Last chosen location is stored in db.
7. User comes back to the website and logs in (same button and pop-up as in 2 and 3)
8. Last chosen location is pre chosen in dashboard (and map?)

**Comment by AlbaLunner** [comment]
I don't think we need email and image in the database since it's personal information. Username and password is sufficient. I also think it should be a register button and a log in button. It can be confusing for the user otherwise. I agree with Ahmed, users should be able to use the website without registering/logging in. Also, only one function (save last plast on map) of the log in is fine.
