### ISSUE TITLE
Design and create contacts page

### ISSUE THREAD

**Issue by BingHawk** [BingHawk/SE4GI_project#34]
- [x] Decide what text to be shown
- [x] Write all texts that are needed and add to database
- [ ] Build the page and display

**Comment by ehorem** [comment]
Text to show:
Image
Name
Bio/education

ex. Evalyn Horemans
Environmental Science, Montreal, Canada

**Comment by ehorem** [comment]
Possible solution draft:

<template>
    <div class = "team">
        <h1 class = "subheading grey--text">Team</h1>

        <v-container class="my-5">

            <v-layout row wrap>
                <v-flex sm2 md3 lg5 v-for="person in team" :key="person.name">
                    <v-card flat class="text-xs-center ma-3">
                        <v-responsive class="pt-4"> 
                            <v-avatar size="100" class="grey lighten-2">
                                <img :src="person.avatar">
                            </v-avatar>
                        </v-responsive>
                        <v-card-text> 
                            <div class="subheading">{{ person.name }}</div>
                            <div class="grey--text">{{ person.name }}</div>
                        </v-card-text>
                    </v-card>
                </v-flex>
            </v-layout>

        </v-container>

    </div>
</template>

<script>
export default{
    data() {
        return {
            team: [
                { name: 'Alba', avatar: '/alba.png' },
                { name: 'Ahmed', avatar: '/ahmed.png'},
                { name: 'Leo', avatar: '/leo.png' },
                { name: 'Evalyn', avatar: '/evalyn.png' },
                { name: 'Mostafa', avatar: '/mostafa.png' }
            ]
        }
    }
}
</script>

**Comment by BingHawk** [comment]
Need to make a /contacts endpoint in the backend
