### ISSUE TITLE
Contact us Endpoint

### ISSUE THREAD

**Issue by AhmedAbdalgader** [BingHawk/SE4GI_project#53]
Make an Endpoint for retrieving the contacts info,

**Comment by AhmedAbdalgader** [comment]
# ROUTED FUNCTIONS FOR RETRIEVING THE DATA FOR THE CONTACT US PAGE
@app.route('/api/contactus', methods=["GET"])
def get_contactsInfo():
        # with app.app_context():
        #test code
            conn = psycopg2.connect(
                database="SE4G", user = MYUSER, password= MYPWRD, host='localhost', port= MYPORT
                )
            cur = conn.cursor()
            cur.execute('SELECT * FROM contacts')
            outcome=cur.fetchall()
            print(outcome)
            outcome2=jsonify(outcome)
            return outcome2

**Comment by BingHawk** [comment]
Done and dusted
